"""传感器物理量程常量：API 入参校验边界与 UI 滑条量程共用单一来源。"""

PRESSURE_LIMIT_MIN = 0.0
PRESSURE_LIMIT_MAX = 10.0
CURRENT_LIMIT_MIN = 0.0
CURRENT_LIMIT_MAX = 50.0

PRESSURE_SLIDER_MIN = 1.0
PRESSURE_SLIDER_MAX = 3.0
CURRENT_SLIDER_MIN = 10.0
CURRENT_SLIDER_MAX = 25.0
